[package]
edition = "2021"
name = "vetovoima"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_prototype_lyon = "0.5"
bevy_rapier2d = {version = "0.13.2", features = ["simd-stable", "debug-render"]}
rand = "0.8.5"
rand_distr = "0.4.3"

# Add this to your Cargo.toml
[profile.dev.package.bevy_rapier2d]
opt-level = 3
